
=pod

=head1 NAME

door - A ANSI C class

=head1 SYNOPSIS

 #include <stdio.h>
 #include "door.h"

 int main(int argc, char **argv) {

     door_t *temp = NULL;

     if ((temp = door_create(NULL))) {

         door_destroy(temp);

     }

     return 0;

 }

=head1 DESCRIPTION

This is a basic class written in ANSI C. It shows a way to implement
object oriented programming. Why do this? It is a nice thought exercise. 

The files door.c and door.h define the class. 

=over 4

=item B<door.h>

This defines the interface to the class. 

=item B<door.c> 

This implements the interface.

=back

=head1 METHODS

=head2 door_t *door_create(NULL)

This method initializes the class. 

=head2 int door_destroy(door_t *self)

This destroys the object. 

=over 4

=item B<self>

A pointer to the door_t object.

=back

=head2 int door_override(door_t *self, item_list_t *items)

This method allows you to override methods. 

=over 4

=item B<self>

A pointer to the door_t object.

=item B<items>

An array of item_list_t data types. The array is 0 terminated.

=back

=head2 int door_compare(door_t *this, door_t *that)

This method allows you to compare one door_t object to another. 

=over 4

=item B<this>

A pointer to a door_t object.

=item B<that>

A pointer to a door_t object.

=back

=head2 char *door_version(door_t *self)

This method returns the version of the library. The version number
follows the guidelines from L<semver.org|https://semver.org/>.

=over 4

=item B<self>

A pointer to the door_t object.

=back

=head1 RETURNS

The method door_create() returns a pointer to a door_t object. 
All other methods return either OK on success or ERR on failure. The 
extended error description can be returned with object_get_error().

=head1 BUILDING

The following assumes a GNU/GCC build environment.

=over 4

=item make

Builds the module and provides an object archive.

=item make clean

Removes cruft from the directory.

=item make man

Builds the man page.

=item make shared

Builds the module and provides a shared library.

=back

=head1 SEE ALSO

=over 4

=item L<object(3)>

=back

=head1 AUTHOR

Kevin L. Esteb, E<lt>kevin@kesteb.usE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2020 by Kevin L. Esteb

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that this copyright notice appears in all copies. The
author makes no representations about the suitability of this software
for any purpose. It is provided "as is" without express or implied
warranty.

=cut

